/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

/**
 *
 * @author NADA
 */
public class kickoff extends javax.swing.JFrame {

    /**
     * Creates new form kickoff
     */
    public kickoff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outofbound = new javax.swing.JButton();
        onsidesuccess = new javax.swing.JButton();
        gamecode = new javax.swing.JButton();
        onside = new javax.swing.JButton();
        playnum = new javax.swing.JButton();
        teamcode = new javax.swing.JButton();
        Kickoff = new javax.swing.JButton();
        attempt = new javax.swing.JButton();
        yards = new javax.swing.JButton();
        faircatch = new javax.swing.JButton();
        touchdown = new javax.swing.JButton();
        downed = new javax.swing.JButton();
        excute = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outofbound.setText("Out Of Bound");
        outofbound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outofboundActionPerformed(evt);
            }
        });

        onsidesuccess.setText("Onside Success");
        onsidesuccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onsidesuccessActionPerformed(evt);
            }
        });

        gamecode.setText("Game Code");
        gamecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamecodeActionPerformed(evt);
            }
        });

        onside.setText("Onside");
        onside.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onsideActionPerformed(evt);
            }
        });

        playnum.setText("Play Number");
        playnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playnumActionPerformed(evt);
            }
        });

        teamcode.setText("Team Code");
        teamcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamcodeActionPerformed(evt);
            }
        });

        Kickoff.setText("Player Code");
        Kickoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KickoffActionPerformed(evt);
            }
        });

        attempt.setText("Attempt");
        attempt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptActionPerformed(evt);
            }
        });

        yards.setText("yards");
        yards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yardsActionPerformed(evt);
            }
        });

        faircatch.setText("Fair Catch");
        faircatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faircatchActionPerformed(evt);
            }
        });

        touchdown.setText("Touchdown");
        touchdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touchdownActionPerformed(evt);
            }
        });

        downed.setText("Downed");
        downed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downedActionPerformed(evt);
            }
        });

        excute.setText("Execute");
        excute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gamecode, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(attempt, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(downed, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(onside, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(271, 271, 271)
                        .addComponent(onsidesuccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(yards, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(playnum, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addGap(21, 21, 21)))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(faircatch, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addGap(68, 68, 68)
                                .addComponent(touchdown, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(outofbound, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addGap(189, 189, 189))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teamcode, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addGap(68, 68, 68)
                                .addComponent(Kickoff, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(excute)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamecode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Kickoff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teamcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attempt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(faircatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(touchdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outofbound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onsidesuccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(downed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88)
                .addComponent(excute)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outofboundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outofboundActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_outofboundActionPerformed

    private void onsidesuccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onsidesuccessActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_onsidesuccessActionPerformed

    private void gamecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamecodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_gamecodeActionPerformed

    private void onsideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onsideActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_onsideActionPerformed

    private void playnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playnumActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_playnumActionPerformed

    private void teamcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamcodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_teamcodeActionPerformed

    private void KickoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KickoffActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_KickoffActionPerformed

    private void attemptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_attemptActionPerformed

    private void yardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yardsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_yardsActionPerformed

    private void faircatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faircatchActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_faircatchActionPerformed

    private void touchdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touchdownActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_touchdownActionPerformed

    private void downedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downedActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_downedActionPerformed

    private void excuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excuteActionPerformed
        // TODO add your handling code here:
        firstframe s=new firstframe();
        s.setVisible(true);
    }//GEN-LAST:event_excuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kickoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kickoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kickoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kickoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kickoff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kickoff;
    private javax.swing.JButton attempt;
    private javax.swing.JButton downed;
    private javax.swing.JButton excute;
    private javax.swing.JButton faircatch;
    private javax.swing.JButton gamecode;
    private javax.swing.JButton onside;
    private javax.swing.JButton onsidesuccess;
    private javax.swing.JButton outofbound;
    private javax.swing.JButton playnum;
    private javax.swing.JButton teamcode;
    private javax.swing.JButton touchdown;
    private javax.swing.JButton yards;
    // End of variables declaration//GEN-END:variables
}
