/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

/**
 *
 * @author NADA
 */
public class rush extends javax.swing.JFrame {

    /**
     * Creates new form rush
     */
    public rush() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yards = new javax.swing.JButton();
        faircatch = new javax.swing.JButton();
        Fumble = new javax.swing.JButton();
        touchdown = new javax.swing.JButton();
        year = new javax.swing.JButton();
        gamecode = new javax.swing.JButton();
        fumblelost = new javax.swing.JButton();
        safety = new javax.swing.JButton();
        playnum = new javax.swing.JButton();
        teamcode = new javax.swing.JButton();
        attempt = new javax.swing.JButton();
        Kickoff = new javax.swing.JButton();
        sack = new javax.swing.JButton();
        excute = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        yards.setText("yards");
        yards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yardsActionPerformed(evt);
            }
        });

        faircatch.setText("Fair Catch");
        faircatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faircatchActionPerformed(evt);
            }
        });

        Fumble.setText("Fumble");
        Fumble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FumbleActionPerformed(evt);
            }
        });

        touchdown.setText("Touchdown");
        touchdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touchdownActionPerformed(evt);
            }
        });

        year.setText("Year");
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        gamecode.setText("Game Code");
        gamecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamecodeActionPerformed(evt);
            }
        });

        fumblelost.setText("Fumble Lost");
        fumblelost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fumblelostActionPerformed(evt);
            }
        });

        safety.setText("Safety");
        safety.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                safetyActionPerformed(evt);
            }
        });

        playnum.setText("Play Number");
        playnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playnumActionPerformed(evt);
            }
        });

        teamcode.setText("Team Code");
        teamcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamcodeActionPerformed(evt);
            }
        });

        attempt.setText("Attempt");
        attempt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptActionPerformed(evt);
            }
        });

        Kickoff.setText("Player Code");
        Kickoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KickoffActionPerformed(evt);
            }
        });

        sack.setText("Sack");

        excute.setText("Execute");
        excute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gamecode, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attempt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fumblelost, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(safety, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yards, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(playnum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fumble, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(touchdown, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(faircatch, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teamcode, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Kickoff, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sack)
                        .addGap(295, 295, 295))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(excute)
                        .addGap(52, 52, 52))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Fumble, Kickoff, attempt, faircatch, fumblelost, gamecode, playnum, sack, safety, teamcode, touchdown, yards, year});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamecode)
                    .addComponent(playnum)
                    .addComponent(Kickoff)
                    .addComponent(teamcode))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attempt)
                    .addComponent(Fumble)
                    .addComponent(touchdown)
                    .addComponent(yards))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faircatch)
                    .addComponent(year)
                    .addComponent(fumblelost)
                    .addComponent(safety))
                .addGap(58, 58, 58)
                .addComponent(sack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excute)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yardsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yardsActionPerformed

    private void faircatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faircatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faircatchActionPerformed

    private void FumbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FumbleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FumbleActionPerformed

    private void touchdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touchdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_touchdownActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void gamecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamecodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gamecodeActionPerformed

    private void fumblelostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fumblelostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fumblelostActionPerformed

    private void safetyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_safetyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_safetyActionPerformed

    private void playnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playnumActionPerformed

    private void teamcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamcodeActionPerformed

    private void attemptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attemptActionPerformed

    private void KickoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KickoffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KickoffActionPerformed

    private void excuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excuteActionPerformed
        // TODO add your handling code here:
        firstframe s=new firstframe();
        s.setVisible(true);
    }//GEN-LAST:event_excuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rush.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rush().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fumble;
    private javax.swing.JButton Kickoff;
    private javax.swing.JButton attempt;
    private javax.swing.JButton excute;
    private javax.swing.JButton faircatch;
    private javax.swing.JButton fumblelost;
    private javax.swing.JButton gamecode;
    private javax.swing.JButton playnum;
    private javax.swing.JButton sack;
    private javax.swing.JButton safety;
    private javax.swing.JButton teamcode;
    private javax.swing.JButton touchdown;
    private javax.swing.JButton yards;
    private javax.swing.JButton year;
    // End of variables declaration//GEN-END:variables
}
