/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

/**
 *
 * @author NADA
 */
public class SQ extends javax.swing.JFrame {

    /**
     * Creates new form SQ
     */
    public SQ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Conference = new javax.swing.JButton();
        Drive = new javax.swing.JButton();
        Game = new javax.swing.JButton();
        Kickoff = new javax.swing.JButton();
        kickoffR = new javax.swing.JButton();
        pass = new javax.swing.JButton();
        play = new javax.swing.JButton();
        Player = new javax.swing.JButton();
        Punt = new javax.swing.JButton();
        PuntR = new javax.swing.JButton();
        Reception = new javax.swing.JButton();
        Rush = new javax.swing.JButton();
        Stadium = new javax.swing.JButton();
        Team = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Conference.setText("Conference");
        Conference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConferenceActionPerformed(evt);
            }
        });

        Drive.setText("Drive");
        Drive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriveActionPerformed(evt);
            }
        });

        Game.setText("Game");
        Game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameActionPerformed(evt);
            }
        });

        Kickoff.setText("Kickoff");
        Kickoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KickoffActionPerformed(evt);
            }
        });

        kickoffR.setText("Kickoff-return");
        kickoffR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kickoffRActionPerformed(evt);
            }
        });

        pass.setText("Pass");
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        play.setText("Play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        Player.setText("Player");
        Player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerActionPerformed(evt);
            }
        });

        Punt.setText("Punt");
        Punt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntActionPerformed(evt);
            }
        });

        PuntR.setText("Punt-Return");
        PuntR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntRActionPerformed(evt);
            }
        });

        Reception.setText("Reception");
        Reception.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceptionActionPerformed(evt);
            }
        });

        Rush.setText("Rush");
        Rush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RushActionPerformed(evt);
            }
        });

        Stadium.setText("Stadium");
        Stadium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StadiumActionPerformed(evt);
            }
        });

        Team.setText("Team");
        Team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(Stadium)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Team, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Conference)
                            .addComponent(kickoffR)
                            .addComponent(Punt))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Rush)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                                .addComponent(PuntR)
                                .addGap(107, 107, 107)
                                .addComponent(Reception))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pass, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Drive, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Game)
                                        .addGap(101, 101, 101)
                                        .addComponent(Kickoff))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(play)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Player)))))))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Conference, Drive, Game, Kickoff, Player, Punt, PuntR, Reception, Rush, Stadium, Team, kickoffR, pass, play});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Conference)
                    .addComponent(Drive)
                    .addComponent(Game)
                    .addComponent(Kickoff))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kickoffR)
                    .addComponent(play)
                    .addComponent(Player)
                    .addComponent(pass))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PuntR)
                    .addComponent(Reception)
                    .addComponent(Punt)
                    .addComponent(Rush))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stadium)
                    .addComponent(Team))
                .addGap(56, 56, 56))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Conference, Drive, Game, Kickoff, Player, Punt, PuntR, Reception, Rush, Stadium, Team, kickoffR, pass, play});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConferenceActionPerformed
        // TODO add your handling code here:
        Conference con=new Conference();
        con.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ConferenceActionPerformed

    private void DriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriveActionPerformed
        // TODO add your handling code here:
        drive d=new drive();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DriveActionPerformed

    private void GameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameActionPerformed
        // TODO add your handling code here:
        game g=new game();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GameActionPerformed

    private void KickoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KickoffActionPerformed
        // TODO add your handling code here:
        kickoff kick=new kickoff();
        kick.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KickoffActionPerformed

    private void kickoffRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kickoffRActionPerformed
        // TODO add your handling code here:
        kickoffre k=new kickoffre();
        k.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kickoffRActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
        pass pass1=new pass();
        pass1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_passActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        play play1=new play();
        play1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_playActionPerformed

    private void PlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerActionPerformed
        // TODO add your handling code here:
        player player1=new player();
        player1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PlayerActionPerformed

    private void PuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntActionPerformed
        // TODO add your handling code here:
        punt punt1=new punt();
        punt1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PuntActionPerformed

    private void RushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RushActionPerformed
        // TODO add your handling code here:
        rush r=new rush();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RushActionPerformed

    private void PuntRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntRActionPerformed
        // TODO add your handling code here:
        puntre pun=new puntre();
        pun.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PuntRActionPerformed

    private void ReceptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceptionActionPerformed
        // TODO add your handling code here:
        reception re=new reception();
        re.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReceptionActionPerformed

    private void StadiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StadiumActionPerformed
        // TODO add your handling code here:
        stadium s=new stadium();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_StadiumActionPerformed

    private void TeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamActionPerformed
        // TODO add your handling code here:
        team t=new team();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TeamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Conference;
    private javax.swing.JButton Drive;
    private javax.swing.JButton Game;
    private javax.swing.JButton Kickoff;
    private javax.swing.JButton Player;
    private javax.swing.JButton Punt;
    private javax.swing.JButton PuntR;
    private javax.swing.JButton Reception;
    private javax.swing.JButton Rush;
    private javax.swing.JButton Stadium;
    private javax.swing.JButton Team;
    private javax.swing.JButton kickoffR;
    private javax.swing.JButton pass;
    private javax.swing.JButton play;
    // End of variables declaration//GEN-END:variables
}
